/**
 * ============================================================================
 * LAUNCH / GROWTH CONFIG — the one file to edit
 * ============================================================================
 *
 * Every value here used to be hand-typed in up to 4-5 different places
 * (src/utils/constants.ts, index.html, functions/api/og/banner.png.tsx,
 * functions/_lib.ts) and drifted every time one copy got updated and the
 * others didn't. This is now the single source of truth. src/, functions/,
 * and index.html (via a Vite build-time token replacement, see
 * vite.config.ts) all read from this file, directly or indirectly.
 *
 * The trait count is NOT here — it is derived from public/traits-manifest.json
 * (generated by scripts/generate-index.mjs from the real files in
 * public/traits/) wherever it's needed, so it can never be hand-typed again.
 *
 * WHY A PLAIN .mjs FILE (not JSON, not TypeScript):
 * The consumers are four different runtimes that don't share a module graph:
 * Vite-bundled browser code (src/), esbuild-bundled Cloudflare Pages
 * Functions (functions/), plain `node scripts/*.mjs` build scripts, and
 * static index.html (which can't import anything at runtime). Plain ESM
 * (this repo's package.json has "type": "module") is the only format all
 * three JS runtimes load natively with zero transform step, and unlike JSON
 * it allows the comments above. index.html can't import even this, so it
 * gets its handful of values injected as text at build time by a small Vite
 * plugin (see vite.config.ts) rather than sharing the module graph.
 *
 * ----------------------------------------------------------------------------
 * WHAT TO EDIT ON LAUNCH DAY (and what each value does):
 *
 *   tokenLive        Master switch. false = every surface on the site shows
 *                     a pre-launch state (no buy button, no contract address,
 *                     no chart). Flip to true once contractAddress is real.
 *   contractAddress  The 0x address from the Pons deployment. Leave "" until
 *                     the token actually exists — showing a stale/wrong
 *                     address is worse than showing nothing.
 *   chartLink        Dexscreener/chart URL for the new pair. Leave "" until
 *                     the pair exists; also feeds the DEXSCREENER social link.
 *   countdownTarget  Unix ms timestamp of the Pons launch slot. Set this and
 *                     flip showCountdown to true to display a countdown.
 *   showCountdown    Whether the countdown banner renders at all.
 *
 * Everything else below (chain facts, launchpad, socials, supply, site URL)
 * is fixed by Pons/Robinhood Chain or by the project itself, not by launch
 * timing — but if any of it changes (a new Telegram, a domain move), this is
 * still the one place to change it.
 * ============================================================================
 */
const launchConfig = {
  // --- Flip these on launch day ---
  tokenLive: false,
  contractAddress: "",
  chartLink: "",
  countdownTarget: 0,
  showCountdown: false,

  // --- Chain facts. Fixed by Pons and Robinhood Chain, not by us. ---
  chain: {
    name: "Robinhood Chain",
    id: 4663,
  },
  launchpad: {
    name: "Pons",
    url: "https://www.ponslaunchpad.com/",
  },
  /** Pons mints a fixed 1B supply straight to the bonding curve. No creator allocation. */
  tokenSupply: 1_000_000_000,
  explorerBase: "https://robinhoodchain.blockscout.com",

  // --- Social ---
  social: {
    twitter: "https://x.com/i/communities/1933201526584963118",
    telegram: "https://t.me/pingtoken",
  },

  // --- Site identity ---
  siteUrl: "https://buildaping.com",
  tokenSymbol: "PING",
  tokenName: "PING",

  // --- Builder ---
  /** Chance a given trait category renders empty, so a random character looks
   *  like a real one. Read by both the client builder (src/components/Builder.tsx)
   *  and the server-side random image endpoint (functions/api/image/random.png.tsx). */
  emptyTraitChance: 0.3,
};

export default launchConfig;
