name = "ping-character-api"
compatibility_date = "2024-01-01"

[env.production]
name = "ping-character-api"

[env.preview]
name = "ping-character-api-preview"

# Pages configuration
pages_build_output_dir = "dist"

# Environment variables (if needed)
[vars]
# Add any environment variables here