import { writeFileSync } from 'fs';

/**
 * Saves the rendered share card to public/opengraph-ping.png.
 *
 * The card is generated by functions/api/og/banner.png.tsx from the same trait
 * art and palette the site uses, but og:image has to be a plain URL a scraper
 * can fetch without running our Functions, and the production domain is not
 * known until launch. So the generated card is snapshotted to a static file.
 *
 * Usage, with `npm run pages:dev` (or wrangler pages dev) already serving:
 *   node scripts/snapshot-og.mjs [origin]
 */

const origin = process.argv[2] ?? 'http://127.0.0.1:8788';
const target = 'public/opengraph-ping.png';

const response = await fetch(`${origin}/api/og/banner.png`);
if (!response.ok) {
  console.error(`Could not render the card: HTTP ${response.status}`);
  console.error(`Is a Pages dev server running on ${origin}?`);
  process.exit(1);
}

const buffer = Buffer.from(await response.arrayBuffer());
if (buffer.subarray(1, 4).toString() !== 'PNG') {
  console.error('Response was not a PNG.');
  process.exit(1);
}

writeFileSync(target, buffer);
console.log(
  `Wrote ${target}: ${buffer.readUInt32BE(16)}x${buffer.readUInt32BE(20)}, ${(buffer.length / 1024).toFixed(0)}KB`
);
